# Data Cleaning – Employee Dataset

This notebook demonstrates a complete data-cleaning workflow for a messy employee dataset using **Pandas and NumPy**.

The workflow covers data loading, exploration, duplicate removal, data-type conversion, invalid-value handling, missing-value treatment, validation, and exporting the cleaned dataset.

# 1. Import Libraries

In [1]:
import pandas as pd 
import numpy as np

# 2. Load the Dataset

In [2]:
df = pd.read_csv("messy_employee_dataset.csv")

In [3]:
df.head()

,Employee_ID,Name,Age,Department,City,Monthly_Salary,Years_At_Company,Join_Date,Email,Employment_Status,Education,Performance_Score
0,E0001,Divya,22,HR,Chennai,NaN,3.5,NaN,employee1@example.com,active,PG,excellent
1,E0002,Meena,NaN,Human Resources,Madurai,"₹45,000",14.7,04/04/2025,NaN,Resigned,UG,1.4
2,E0003,Meena,thirty,Marketing,Bengaluru,25695,11.5,not a date,employee3@example.com,Left,NaN,NaN
3,E0004,anitha,NaN,it,chennai,-25000,-2,"Nov 30, 2021",missing-email,ACTIVE,Post Graduate,NaN
4,E0005,Kavin,-5,IT,Bengaluru,75570,5.7,"Jul 07, 2025",NaN,Left,NaN,7

In [4]:
df.tail()

,Employee_ID,Name,Age,Department,City,Monthly_Salary,Years_At_Company,Join_Date,Email,Employment_Status,Education,Performance_Score
1025,E0358,Nila,49,Marketing,Salem,67666,five,not a date,NaN,NaN,Post Graduate,7
1026,E0566,Priya,150,Human Resources,HYDERABAD,NaN,NaN,"Aug 19, 2024",employee566@example.com,Left,UG,7
1027,E0768,Ahalya,50,IT,Coimbatore,-25000,NaN,2024-04-01,NaN,Active,PG,NaN
1028,E0643,Vijay,150,Marketing,Chennai,not disclosed,6.3,2025-10-01,NaN,ACTIVE,Diploma,7
1029,E0608,Vijay,-5,Marketing,Bengaluru,NaN,five,NaN,NaN,On Leave,UG,0

# 3. Explore Dataset Structure

In [5]:
df.shape

(1030, 12)

In [6]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'City', 'Monthly_Salary',
       'Years_At_Company', 'Join_Date', 'Email', 'Employment_Status',
       'Education', 'Performance_Score'],
      dtype='str')

In [7]:
df.dtypes

Employee_ID          str
Name                 str
Age                  str
Department           str
City                 str
Monthly_Salary       str
Years_At_Company     str
Join_Date            str
Email                str
Employment_Status    str
Education            str
Performance_Score    str
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1021 non-null   str
 1   Name               1030 non-null   str
 2   Age                852 non-null    str
 3   Department         930 non-null    str
 4   City               899 non-null    str
 5   Monthly_Salary     844 non-null    str
 6   Years_At_Company   821 non-null    str
 7   Join_Date          824 non-null    str
 8   Email              766 non-null    str
 9   Employment_Status  918 non-null    str
 10  Education          877 non-null    str
 11  Performance_Score  832 non-null    str
dtypes: str(12)
memory usage: 96.7 KB

# 5. Explore Missing Values

In [9]:
df.isna().sum()

Employee_ID            9
Name                   0
Age                  178
Department           100
City                 131
Monthly_Salary       186
Years_At_Company     209
Join_Date            206
Email                264
Employment_Status    112
Education            153
Performance_Score    198
dtype: int64

# 4. Check and Remove Duplicate Rows

In [10]:
df.duplicated().sum()

np.int64(30)

In [11]:
df[df.duplicated(keep = False)]

,Employee_ID,Name,Age,Department,City,Monthly_Salary,Years_At_Company,Join_Date,Email,Employment_Status,Education,Performance_Score
11,E0012,ROHAN,NaN,HR,chennai,NaN,40,not a date,NaN,Active,ug,3.9
25,E0026,Kavin,NaN,it,Bengaluru,"₹45,000",NaN,not a date,Employee26@Example.com,active,PG,NaN
120,E0121,Sanjay,60,Sales,Madurai,not disclosed,40,2024-10-02,Employee121@Example.com,Active,Diploma,7
121,E0122,Priya,-5,sales,Salem,54282,NaN,2021-05-08,NaN,active,NaN,0
173,E0174,Divya,NaN,it,chennai,36637,-2,2025-02-10,employee174@example.com,left,NaN,4.9
191,E0192,Vijay,32,hr,NaN,not disclosed,five,NaN,Employee192@Example.com,ACTIVE,Diploma,NaN
230,E0231,Priya,150,NaN,Coimbatore,53294,13.3,not a date,NaN,ACTIVE,UG,excellent
357,E0358,Nila,49,Marketing,Salem,67666,five,not a date,NaN,NaN,Post Graduate,7
372,E0373,Kavin,45,NaN,Bengaluru,105269,-2,NaN,Employee373@Example.com,Active,Post Graduate,0
374,E0375,Kavin,34,Sales,Bengaluru,-25000,five,not a date,missing-email,NaN,ug,3.0
392,E0393,Ahalya,NaN,IT,chennai,73008,10.6,2021-06-09,NaN,Active,NaN,3.1
417,E0418,ROHAN,23,it,chennai,81746,-2,not a date,employee418@example.com,Resigned,ug,excellent
419,E0420,Arun,54,hr,HYDERABAD,-25000,NaN,18/06/2022,missing-email,Resigned,PG,7
464,E0465,Ahalya,NaN,Finance,Salem,NaN,40,NaN,NaN,ACTIVE,UG,7
544,E0545,Kavin,54,hr,Madurai,60001,-2,"Apr 13, 2023",employee545@example.com,active,PG,3.3
565,E0566,Priya,150,Human Resources,HYDERABAD,NaN,NaN,"Aug 19, 2024",employee566@example.com,Left,UG,7
607,E0608,Vijay,-5,Marketing,Bengaluru,NaN,five,NaN,NaN,On Leave,UG,0
642,E0643,Vijay,150,Marketing,Chennai,not disclosed,6.3,2025-10-01,NaN,ACTIVE,Diploma,7
659,E0660,Nila,150,IT,HYDERABAD,"₹45,000",0.2,"Jun 02, 2026",NaN,Active,Post Graduate,0
730,E0731,Arun,NaN,Human Resources,NaN,not disclosed,40,2026-04-21,missing-email,active,Diploma,excellent
757,E0758,Nila,43,Sales,chennai,NaN,NaN,2021-07-26,employee758@example.com,Resigned,Diploma,NaN
759,E0760,Nila,150,NaN,chennai,NaN,40,2024-04-23,employee760@example.com,ACTIVE,PG,7
767,E0768,Ahalya,50,IT,Coimbatore,-25000,NaN,2024-04-01,NaN,Active,PG,NaN
772,E0773,Meena,NaN,HR,HYDERABAD,41710,five,09/04/2022,NaN,left,ug,7
814,E0815,Divya,150,NaN,Madurai,"₹45,000",NaN,NaN,Employee815@Example.com,ACTIVE,ug,NaN
841,E0842,Priya,150,FINANCE,chennai,"₹45,000",10.0,not a date,NaN,Left,ug,0
845,E0846,Priya,-5,hr,Chennai,86247,40,not a date,NaN,On Leave,UG,NaN
944,E0945,Ahalya,150,FINANCE,chennai,121443,five,29/11/2025,Employee945@Example.com,Left,Post Graduate,0
955,E0956,Priya,26,sales,Madurai,58223,-2,"Apr 22, 2026",missing-email,Resigned,Diploma,NaN
956,E0957,Vijay,33,FINANCE,Chennai,"₹45,000",40,"Jun 11, 2025",missing-email,Left,NaN,NaN
1000,E0842,Priya,150,FINANCE,chennai,"₹45,000",10.0,not a date,NaN,Left,ug,0
1001,E0957,Vijay,33,FINANCE,Chennai,"₹45,000",40,"Jun 11, 2025",missing-email,Left,NaN,NaN
1002,E0545,Kavin,54,hr,Madurai,60001,-2,"Apr 13, 2023",employee545@example.com,active,PG,3.3
1003,E0174,Divya,NaN,it,chennai,36637,-2,2025-02-10,employee174@example.com,left,NaN,4.9
1004,E0760,Nila,150,NaN,chennai,NaN,40,2024-04-23,employee760@example.com,ACTIVE,PG,7
1005,E0956,Priya,26,sales,Madurai,58223,-2,"Apr 22, 2026",missing-email,Resigned,Diploma,NaN
1006,E0122,Priya,-5,sales,Salem,54282,NaN,2021-05-08,NaN,active,NaN,0
1007,E0231,Priya,150,NaN,Coimbatore,53294,13.3,not a date,NaN,ACTIVE,UG,excellent
1008,E0012,ROHAN,NaN,HR,chennai,NaN,40,not a date,NaN,Active,ug,3.9
1009,E0121,Sanjay,60,Sales,Madurai,not disclosed,40,2024-10-02,Employee121@Example.com,Active,Diploma,7
1010,E0660,Nila,150,IT,HYDERABAD,"₹45,000",0.2,"Jun 02, 2026",NaN,Active,Post Graduate,0
1011,E0420,Arun,54,hr,HYDERABAD,-25000,NaN,18/06/2022,missing-email,Resigned,PG,7
1012,E0192,Vijay,32,hr,NaN,not disclosed,five,NaN,Employee192@Example.com,ACTIVE,Diploma,NaN
1013,E0945,Ahalya,150,FINANCE,chennai,121443,five,29/11/2025,Employee945@Example.com,Left,Post Graduate,0
1014,E0393,Ahalya,NaN,IT,chennai,73008,10.6,2021-06-09,NaN,Active,NaN,3.1
1015,E0418,ROHAN,23,it,chennai,81746,-2,not a date,employee418@example.com,Resigned,ug,excellent
1016,E0846,Priya,-5,hr,Chennai,86247,40,not a date,NaN,On Leave,UG,NaN
1017,E0815,Divya,150,NaN,Madurai,"₹45,000",NaN,NaN,Employee815@Example.com,ACTIVE,ug,NaN
1018,E0773,Meena,NaN,HR,HYDERABAD,41710,five,09/04/2022,NaN,left,ug,7
1019,E0375,Kavin,34,Sales,Bengaluru,-25000,five,not a date,missing-email,NaN,ug,3.0
1020,E0026,Kavin,NaN,it,Bengaluru,"₹45,000",NaN,not a date,Employee26@Example.com,active,PG,NaN
1021,E0465,Ahalya,NaN,Finance,Salem,NaN,40,NaN,NaN,ACTIVE,UG,7
1022,E0373,Kavin,45,NaN,Bengaluru,105269,-2,NaN,Employee373@Example.com,Active,Post Graduate,0
1023,E0731,Arun,NaN,Human Resources,NaN,not disclosed,40,2026-04-21,missing-email,active,Diploma,excellent
1024,E0758,Nila,43,Sales,chennai,NaN,NaN,2021-07-26,employee758@example.com,Resigned,Diploma,NaN
1025,E0358,Nila,49,Marketing,Salem,67666,five,not a date,NaN,NaN,Post Graduate,7
1026,E0566,Priya,150,Human Resources,HYDERABAD,NaN,NaN,"Aug 19, 2024",employee566@example.com,Left,UG,7
1027,E0768,Ahalya,50,IT,Coimbatore,-25000,NaN,2024-04-01,NaN,Active,PG,NaN
1028,E0643,Vijay,150,Marketing,Chennai,not disclosed,6.3,2025-10-01,NaN,ACTIVE,Diploma,7
1029,E0608,Vijay,-5,Marketing,Bengaluru,NaN,five,NaN,NaN,On Leave,UG,0

# 6. Clean Employee ID

In [12]:
df[df["Employee_ID"].isna()]

,Employee_ID,Name,Age,Department,City,Monthly_Salary,Years_At_Company,Join_Date,Email,Employment_Status,Education,Performance_Score
110,NaN,ROHAN,150,it,Bengaluru,NaN,five,15/10/2022,NaN,NaN,NaN,7
147,NaN,Nila,thirty,Human Resources,Chennai,"₹45,000",40,2023-01-18,Employee148@Example.com,NaN,NaN,0
221,NaN,Kavin,150,hr,Chennai,NaN,-2,"Jan 08, 2023",NaN,Active,PG,NaN
332,NaN,Rahul,150,it,Bengaluru,"₹45,000",five,NaN,NaN,Left,NaN,excellent
369,NaN,Ahalya,21,sales,Chennai,NaN,five,NaN,Employee370@Example.com,Active,ug,excellent
443,NaN,Arun,-5,hr,Madurai,not disclosed,0.8,not a date,employee444@example.com,NaN,Diploma,0
776,NaN,Sanjay,NaN,sales,Coimbatore,-25000,23.7,"Feb 21, 2023",employee777@example.com,NaN,Diploma,1.9
961,NaN,Meena,NaN,NaN,chennai,52032,40,not a date,missing-email,On Leave,UG,NaN
998,NaN,Sanjay,NaN,Human Resources,Chennai,35725,five,2021-06-02,NaN,Left,Post Graduate,0

In [13]:
df = df.drop_duplicates()

In [14]:
df.shape

(1000, 12)

# 8. Clean Age Column

#Handling invalid data in age column

In [15]:
print(df["Age"].unique())

<StringArray>
[    '22',      nan, 'thirty',     '-5',     '48',     '21',     '40',
     '55',     '58',    '150',     '50',     '56',     '23',     '33',
     '25',     '36',     '52',     '57',     '38',     '26',     '53',
     '60',     '39',     '27',     '59',     '28',     '30',     '37',
     '31',     '54',     '29',     '24',     '43',     '47',     '42',
     '49',     '46',     '32',     '51',     '41',     '45',     '34',
     '35',     '44']
Length: 44, dtype: str

In [16]:
df["Age"] = pd.to_numeric(df["Age"],errors = 'coerce')

In [17]:
print(df["Age"].unique())

[ 22.  nan  -5.  48.  21.  40.  55.  58. 150.  50.  56.  23.  33.  25.
  36.  52.  57.  38.  26.  53.  60.  39.  27.  59.  28.  30.  37.  31.
  54.  29.  24.  43.  47.  42.  49.  46.  32.  51.  41.  45.  34.  35.
  44.]

In [18]:
print(df["Age"].dtype)

float64

In [19]:
print(df["Age"].isnull().sum())

337

In [20]:
print("Minimum Age:",df["Age"].min())
print("Maximum Age:",df["Age"].max())

Minimum Age: -5.0
Maximum Age: 150.0

In [21]:
invalid_ages = df.loc[~df["Age"].between(18,65),"Age"]
print(invalid_ages.value_counts())

Age
 150.0    164
-5.0      158
Name: count, dtype: int64

In [22]:
print("Minimum Age:",df["Age"].min())
print("Maximum Age:",df["Age"].max())
print("Missing ages:",df["Age"].isna().sum())

Minimum Age: -5.0
Maximum Age: 150.0
Missing ages: 337

In [23]:
df.loc[df["Age"]< 18,"Age"] = np.nan
df.loc[df["Age"]> 65,"Age"] = np.nan

In [24]:
print("Minimum Ages:",df["Age"].min())
print("Maximum Age:",df["Age"].max())
print("Missing values:",df["Age"].isna().sum())

Minimum Ages: 21.0
Maximum Age: 60.0
Missing values: 659

# 11. Clean Monthly Salary

In [25]:
print(df["Monthly_Salary"].unique())

<StringArray>
[            nan,       '₹45,000',         '25695',        '-25000',
         '75570',         '54438', 'not disclosed',         '81143',
        '100209',         '97303',
 ...
         '51760',         '53781',         '76904',        '100233',
         '20853',         '73888',         '41531',         '72793',
         '37445',         '35725']
Length: 353, dtype: str

In [26]:
print(df["Monthly_Salary"].value_counts(dropna = False).head(15))

Monthly_Salary
NaN              180
₹45,000          163
-25000           161
not disclosed    147
25695              1
75570              1
54438              1
81143              1
100209             1
97303              1
146065             1
47235              1
57056              1
132264             1
47743              1
Name: count, dtype: int64

In [27]:
df["Monthly_Salary"] = (df["Monthly_Salary"]
                        .astype(str)
                        .str.replace("₹","",regex = False)
                        .str.replace(",","",regex = False)
                        .str.strip())

In [28]:
df["Monthly_Salary"] = pd.to_numeric(df["Monthly_Salary"],errors='coerce')

In [29]:
print("maximum salary:",df["Monthly_Salary"].max())
print("minimum salary:",df["Monthly_Salary"].min())
print("Data Type:",df["Monthly_Salary"].dtype)
print("missing_Values:",df["Monthly_Salary"].isna().sum())

maximum salary: 149935.0
minimum salary: -25000.0
Data Type: float64
missing_Values: 327

In [30]:
df.loc[df["Monthly_Salary"] < 0,"Monthly_Salary"] = np.nan

In [31]:
print("missing_Values:",df["Monthly_Salary"].isna().sum())

missing_Values: 488

In [32]:
df["Monthly_Salary"].unique()

array([    nan,  45000.,  25695.,  75570.,  54438.,  81143., 100209.,
        97303., 146065.,  47235.,  57056., 132264.,  47743., 149672.,
        22875.,  80852.,  80372.,  42439.,  99906.,  24882.,  86910.,
        43218.,  57419.,  36750.,  67749., 116281.,  22154.,  42949.,
        41842., 146765., 131408.,  97383.,  49145.,  89203.,  73334.,
        54282.,  24222.,  42238.,  35376., 148358.,  55798., 132580.,
       112350., 126477.,  38242.,  41542.,  89168.,  40802.,  46518.,
        52648.,  63290.,  58024.,  36637., 116638.,  89291.,  85848.,
        70165.,  64520.,  83858., 110073.,  41090.,  66911.,  41695.,
        95083.,  59532.,  22348.,  76841.,  82180.,  21671.,  33373.,
       125815.,  21526.,  27393.,  67617.,  53294.,  92954.,  49287.,
       102131.,  40943.,  25965.,  37875.,  58096.,  60065., 149366.,
        83113.,  20157.,  42214.,  95136.,  58893., 100746.,  39116.,
        66018.,  75288.,  67600.,  62723.,  88610.,  26319.,  52396.,
        83075.,  81724.,  20094.,  68374.,  88969.,  74314., 122645.,
        56712.,  89122.,  85549.,  59431.,  52483.,  28095., 102793.,
        57851.,  96234., 114618.,  83394.,  91826.,  25771.,  32178.,
        34253., 114789., 132487.,  51031., 139880.,  77695.,  20221.,
        35963.,  83692.,  67666.,  64265.,  51808.,  74555.,  31537.,
        72554., 136789., 103376.,  82818.,  41207., 105269.,  88247.,
       101943.,  47442., 139491.,  60838.,  73008.,  85619.,  68033.,
        33332.,  44110.,  58477.,  23525.,  30048.,  29070.,  82288.,
       133973.,  81746.,  26828.,  24021.,  79468.,  62368.,  61358.,
        26380.,  92694., 129388.,  74558., 134019.,  65252.,  68404.,
        83539., 125117.,  56356., 142737.,  73411.,  66061.,  59738.,
        77147.,  61062.,  68457.,  47425.,  81866., 120525.,  85860.,
        57737.,  71583.,  35031.,  88534.,  22204.,  28652.,  70930.,
        46789.,  72122.,  46624.,  19894.,  82406.,  82429.,  76602.,
        40014., 120593., 142223.,  55877.,  72061.,  84283.,  29248.,
        46833.,  89006.,  65242.,  26929.,  60001.,  75572.,  58294.,
        82822.,  56987.,  26832.,  45287.,  44928.,  95305.,  33137.,
        21538.,  88112.,  49607.,  78323.,  53020.,  69474., 149935.,
        46416.,  71202., 133879.,  80591.,  47870.,  57125.,  65135.,
       108655.,  20725.,  82642., 113496.,  94232.,  55412., 134343.,
       138153.,  56482., 123846., 130069., 120347.,  77704.,  21952.,
        82744.,  24272., 107540.,  44475.,  66090.,  48863.,  84254.,
        54289.,  23250.,  88778.,  82124.,  24394.,  40569.,  60341.,
        47611.,  37025., 149058.,  91849.,  64272., 124740.,  79178.,
       133355.,  65116., 137554.,  71126.,  62538., 112474.,  38378.,
        65609.,  55838., 137913.,  41710.,  53683.,  90212.,  51626.,
        23164.,  80057.,  53031.,  65013.,  39597.,  61111.,  29723.,
        48495.,  46853.,  29243.,  92633.,  30958.,  49428.,  27254.,
        56442., 108132.,  71729.,  63392.,  28323.,  26879.,  23081.,
        86247.,  20939.,  23870.,  89600.,  50345.,  67011., 147814.,
        25488., 145466.,  54442.,  28758.,  22571.,  51991.,  31124.,
        27546., 131615.,  96732.,  44387., 111651.,  94396.,  48859.,
        82026.,  62848.,  85765.,  21862., 136727.,  59348.,  38667.,
        55264.,  36337.,  46144.,  80051., 121443.,  67917.,  86368.,
        33915.,  69556.,  58223.,  52032., 108647.,  51760.,  53781.,
        76904., 100233.,  20853.,  73888.,  41531.,  72793.,  37445.,
        35725.])

# 9. Clean Department Column

Department Column Data cleaning

In [33]:
df["Department"].unique()

<StringArray>
[             'HR', 'Human Resources',       'Marketing',             'it ',
              'IT',         'Finance',              'hr',         'FINANCE',
           'Sales',          ' sales',               nan]
Length: 11, dtype: str

In [34]:
original_df = pd.read_csv("messy_employee_dataset.csv")

df["Department"] = original_df.loc[
    df.index, "Department"
]

In [35]:
df["Department"].unique()

<StringArray>
[             'HR', 'Human Resources',       'Marketing',             'it ',
              'IT',         'Finance',              'hr',         'FINANCE',
           'Sales',          ' sales',               nan]
Length: 11, dtype: str

In [36]:
df["Department"] = df["Department"].str.strip().replace({"Human Resources" : "HR",
                          "sales" : "Sales",
                          "hr":"HR",
                          "it" : "IT",
                          "FINANCE" : "Finance"})

In [37]:
df["Department"].unique()

<StringArray>
['HR', 'Marketing', 'IT', 'Finance', 'Sales', nan]
Length: 6, dtype: str

In [38]:
df["Department"].value_counts(dropna = False)

Department
HR           255
IT           194
Sales        189
Finance      165
Marketing    101
NaN           96
Name: count, dtype: int64

In [39]:
print(df["Department"].dtype)

str

# 7. Clean Name Column

Data Cleaning (Name Column)

In [40]:
df["Name"].unique()

<StringArray>
[    'Divya',     'Meena', '  anitha ',     'Kavin',      'Nila',     'ROHAN',
     'Rahul',      'Arun',     'Priya',    'Sanjay',     'Vijay',    'Ahalya']
Length: 12, dtype: str

In [41]:
df["Name"] = df["Name"].str.strip().str.title()

In [42]:
df["Name"].unique()

<StringArray>
[ 'Divya',  'Meena', 'Anitha',  'Kavin',   'Nila',  'Rohan',  'Rahul',
   'Arun',  'Priya', 'Sanjay',  'Vijay', 'Ahalya']
Length: 12, dtype: str

In [43]:
df["Name"].isna().sum()

np.int64(0)

# 10. Clean City Column

Data Cleaning (City)

In [44]:
df["City"].unique()

<StringArray>
[   'Chennai',    'Madurai',  'Bengaluru',  ' chennai ',      'Salem',
 'Coimbatore',          nan,  'HYDERABAD']
Length: 8, dtype: str

In [45]:
df["City"] = df["City"].str.strip().str.title()

In [46]:
df["City"].unique()

<StringArray>
['Chennai', 'Madurai', 'Bengaluru', 'Salem', 'Coimbatore', nan, 'Hyderabad']
Length: 7, dtype: str

Years at Company (Data Cleaning)

# 12. Clean Years at Company

In [47]:
df["Years_At_Company"].unique()

<StringArray>
[ '3.5', '14.7', '11.5',   '-2',  '5.7', 'five', '12.7', '18.3',  '1.7',
   '40',
 ...
 '12.0', '19.9',  '1.3', '18.6',  '0.1', '13.4', '24.3',  '0.5', '23.2',
  '3.2']
Length: 141, dtype: str

In [48]:
df["Years_At_Company"] = pd.to_numeric(df["Years_At_Company"],errors = 'coerce')

In [49]:
df["Years_At_Company"].unique()

array([ 3.5, 14.7, 11.5, -2. ,  5.7,  nan, 12.7, 18.3,  1.7, 40. , 25. ,
       15.3,  5. ,  2.7, 19.8,  6.3,  5.3, 21.5,  9.9,  6.9,  4.4, 18.9,
       21.1,  8. ,  3.4,  1.1,  7.7, 23.7, 10.5, 17.1, 12.1, 10.7,  2.1,
       16.4,  6.2,  0.4, 20.1, 21.3,  1.9,  5.9, 16. , 15.9, 17.8,  3.8,
        2.2, 11.3, 13.3, 13.1, 22.8, 24.1,  3.7, 11.7, 17.9, 10.4,  8.6,
       13.9, 10.3,  0. , 21.2, 16.6,  6.7, 23.9, 16.2,  8.2,  9.2,  5.1,
       10.6, 16.7,  4.7, 12.5,  8.5,  1.4,  7.1,  0.3,  0.8, 14.3,  4.5,
       17. ,  5.8, 11.9, 12.9, 10. , 17.6, 22.1, 21.4,  7.3, 14.1, 24.6,
        3.3, 11.1, 15.7,  6.8, 15.6, 13.2, 20.6,  9.6,  6.6, 18.5, 20.8,
       15.5, 17.7,  5.2,  8.8, 14.2,  3.1,  0.2, 15.2,  0.7, 22.9, 20.2,
        7.6,  2.9,  8.3, 22. , 19.3, 18.7, 14.4, 20.7, 19.7, 16.5, 23.6,
        8.1,  1.2, 22.2, 22.4,  4.6, 12.3, 19. , 13. , 18.2, 12. , 19.9,
        1.3, 18.6,  0.1, 13.4, 24.3,  0.5, 23.2,  3.2])

In [50]:
df["Years_At_Company"].dtype

dtype('float64')

In [51]:
df.loc[df["Years_At_Company"]< 0 ,"Years_At_Company"] = np.nan

In [52]:
print("maximum Years at company:",df["Years_At_Company"].max())
print("minimum Years at company:",df["Years_At_Company"].min())

maximum Years at company: 40.0
minimum Years at company: 0.0

In [53]:
print("Data Type:",df["Years_At_Company"].dtype)
print("missing Values:",df["Years_At_Company"].isna().sum())

Data Type: float64
missing Values: 593

Join Date(Data Cleaning)

# 13. Clean Join Date

In [54]:
df["Join_Date"].unique()

<StringArray>
[           nan,   '04/04/2025',   'not a date', 'Nov 30, 2021',
 'Jul 07, 2025', 'Mar 29, 2023', 'Nov 18, 2025', 'Oct 27, 2025',
   '2022-05-27',   '2022-09-06',
 ...
 'Aug 31, 2022',   '2022-05-13',   '03/11/2022', 'Oct 09, 2025',
   '11/09/2025', 'Oct 01, 2025',   '08/03/2023', 'Nov 29, 2023',
   '2021-06-02', 'Jun 30, 2021']
Length: 568, dtype: str

In [55]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors = 'coerce')

In [56]:
df["Join_Date"].unique()

<DatetimeArray>
[                'NaT', '2025-04-04 00:00:00', '2024-07-11 00:00:00',
 '2024-08-11 00:00:00', '2025-08-02 00:00:00', '2025-11-01 00:00:00',
 '2021-01-06 00:00:00', '2023-07-05 00:00:00', '2022-06-05 00:00:00',
 '2023-05-09 00:00:00', '2022-08-05 00:00:00', '2023-10-12 00:00:00',
 '2024-10-09 00:00:00', '2024-05-02 00:00:00', '2021-03-01 00:00:00',
 '2024-10-07 00:00:00', '2026-02-03 00:00:00', '2025-02-05 00:00:00',
 '2024-07-05 00:00:00', '2023-07-04 00:00:00', '2025-12-04 00:00:00',
 '2025-05-04 00:00:00', '2025-07-11 00:00:00', '2022-08-03 00:00:00',
 '2022-06-07 00:00:00', '2025-04-05 00:00:00', '2025-05-03 00:00:00',
 '2022-07-04 00:00:00', '2025-03-12 00:00:00', '2026-11-01 00:00:00',
 '2022-01-01 00:00:00', '2023-03-08 00:00:00', '2021-01-07 00:00:00',
 '2022-12-06 00:00:00', '2021-11-08 00:00:00', '2023-12-10 00:00:00',
 '2023-02-01 00:00:00', '2025-09-06 00:00:00', '2025-01-01 00:00:00',
 '2022-08-09 00:00:00', '2021-07-12 00:00:00', '2023-09-01 00:00:00',
 '2024-09-10 00:00:00', '2023-04-03 00:00:00', '2025-12-01 00:00:00',
 '2022-05-08 00:00:00', '2022-02-06 00:00:00', '2025-08-08 00:00:00',
 '2021-05-09 00:00:00', '2022-12-11 00:00:00', '2022-05-02 00:00:00',
 '2022-02-08 00:00:00', '2024-08-08 00:00:00', '2023-05-10 00:00:00',
 '2025-05-10 00:00:00', '2025-03-03 00:00:00', '2022-09-04 00:00:00',
 '2022-07-07 00:00:00', '2023-01-11 00:00:00', '2025-05-09 00:00:00',
 '2025-11-03 00:00:00', '2025-09-10 00:00:00', '2026-02-01 00:00:00',
 '2026-03-03 00:00:00', '2025-11-10 00:00:00', '2021-12-06 00:00:00',
 '2021-10-05 00:00:00', '2023-03-10 00:00:00', '2023-05-11 00:00:00',
 '2022-04-07 00:00:00', '2023-08-09 00:00:00', '2026-07-01 00:00:00',
 '2022-03-04 00:00:00', '2023-12-03 00:00:00', '2026-02-02 00:00:00',
 '2024-05-01 00:00:00', '2022-06-02 00:00:00', '2021-09-09 00:00:00',
 '2026-04-04 00:00:00', '2022-03-11 00:00:00', '2025-11-09 00:00:00',
 '2023-08-03 00:00:00']
Length: 82, dtype: datetime64[us]

In [57]:
print("Missing Values:",df["Join_Date"].isna().sum())

Missing Values: 916

In [58]:
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    format="mixed",
    errors="coerce",
    dayfirst=False
)

print("Data Type:", df["Join_Date"].dtype)
print("Missing Values:", df["Join_Date"].isna().sum())

Data Type: datetime64[us]
Missing Values: 916

In [59]:
print("Valid Dates:", df["Join_Date"].notna().sum())
print("Earliest Join Date:", df["Join_Date"].min())
print("Latest Join Date:", df["Join_Date"].max())

Valid Dates: 84
Earliest Join Date: 2021-01-06 00:00:00
Latest Join Date: 2026-11-01 00:00:00

# 14. Clean Email Column

Email column Data Cleaning

In [60]:
df["Email"].unique()

<StringArray>
[    'employee1@example.com',                         nan,
     'employee3@example.com',             'missing-email',
   ' Employee6@Example.com ',     'employee7@example.com',
   ' Employee8@Example.com ',   ' Employee9@Example.com ',
    'employee11@example.com',  ' Employee15@Example.com ',
 ...
   'employee974@example.com',   'employee978@example.com',
 ' Employee985@Example.com ', ' Employee986@Example.com ',
   'employee987@example.com',   'employee988@example.com',
 ' Employee989@Example.com ',   'employee990@example.com',
   'employee991@example.com', ' Employee997@Example.com ']
Length: 507, dtype: str

In [61]:
df["Email"] = df["Email"].str.strip().str.lower()

In [62]:
df["Email"].unique()

<StringArray>
[  'employee1@example.com',                       nan,
   'employee3@example.com',           'missing-email',
   'employee6@example.com',   'employee7@example.com',
   'employee8@example.com',   'employee9@example.com',
  'employee11@example.com',  'employee15@example.com',
 ...
 'employee974@example.com', 'employee978@example.com',
 'employee985@example.com', 'employee986@example.com',
 'employee987@example.com', 'employee988@example.com',
 'employee989@example.com', 'employee990@example.com',
 'employee991@example.com', 'employee997@example.com']
Length: 507, dtype: str

In [63]:
df["Email"] = df["Email"].replace("missing-email",np.nan)

In [64]:
print("Total rows:", len(df))
print("Unique emails:", df["Email"].nunique())
print("Missing emails:", df["Email"].isna().sum())

Total rows: 1000
Unique emails: 505
Missing emails: 495

Employee Status(Data Cleaning)

In [65]:
df.head(23)

,Employee_ID,Name,Age,Department,City,Monthly_Salary,Years_At_Company,Join_Date,Email,Employment_Status,Education,Performance_Score
0,E0001,Divya,22.0,HR,Chennai,NaN,3.5,NaT,employee1@example.com,active,PG,excellent
1,E0002,Meena,NaN,HR,Madurai,45000.0,14.7,2025-04-04,NaN,Resigned,UG,1.4
2,E0003,Meena,NaN,Marketing,Bengaluru,25695.0,11.5,NaT,employee3@example.com,Left,NaN,NaN
3,E0004,Anitha,NaN,IT,Chennai,NaN,NaN,NaT,NaN,ACTIVE,Post Graduate,NaN
4,E0005,Kavin,NaN,IT,Bengaluru,75570.0,5.7,NaT,NaN,Left,NaN,7
5,E0006,Nila,NaN,Finance,Chennai,54438.0,NaN,NaT,employee6@example.com,Active,UG,NaN
6,E0007,Rohan,48.0,HR,Salem,NaN,NaN,NaT,employee7@example.com,Resigned,UG,NaN
7,E0008,Rahul,21.0,HR,Chennai,NaN,12.7,NaT,employee8@example.com,Resigned,ug,0
8,E0009,Anitha,40.0,Finance,Coimbatore,81143.0,18.3,NaT,employee9@example.com,left,Post Graduate,7
9,E0010,Arun,55.0,IT,Chennai,45000.0,NaN,NaT,NaN,Resigned,UG,NaN
10,E0011,Arun,58.0,IT,NaN,NaN,1.7,NaT,employee11@example.com,Left,Post Graduate,excellent
11,E0012,Rohan,NaN,HR,Chennai,NaN,40.0,NaT,NaN,Active,ug,3.9
12,E0013,Kavin,NaN,HR,Chennai,45000.0,40.0,NaT,NaN,active,PG,7
13,E0014,Rohan,NaN,Finance,NaN,45000.0,40.0,NaT,NaN,ACTIVE,PG,2.2
14,E0015,Nila,58.0,HR,Coimbatore,100209.0,NaN,NaT,employee15@example.com,active,Post Graduate,NaN
15,E0016,Arun,NaN,Marketing,Bengaluru,NaN,NaN,NaT,NaN,Left,Diploma,0
16,E0017,Meena,50.0,HR,Bengaluru,NaN,25.0,NaT,employee17@example.com,active,PG,NaN
17,E0018,Kavin,55.0,HR,Coimbatore,97303.0,NaN,NaT,employee18@example.com,left,Diploma,0
18,E0019,Rahul,NaN,HR,Salem,146065.0,40.0,NaT,employee19@example.com,ACTIVE,NaN,7
19,E0020,Priya,56.0,HR,Salem,NaN,NaN,NaT,employee20@example.com,Resigned,UG,NaN
20,E0021,Rohan,NaN,Sales,Hyderabad,NaN,NaN,NaT,employee21@example.com,Left,Diploma,1.6
21,E0022,Rahul,NaN,IT,Chennai,45000.0,NaN,NaT,employee22@example.com,left,Diploma,7
22,E0023,Rohan,55.0,Sales,Hyderabad,NaN,NaN,NaT,NaN,active,ug,NaN

# 15. Clean Employment Status

In [66]:
df["Employment_Status"].unique()

<StringArray>
['active', 'Resigned', 'Left', 'ACTIVE', 'Active', 'left', 'On Leave', nan]
Length: 8, dtype: str

In [67]:
print(df.columns)

Index(['Employee_ID', 'Name', 'Age', 'Department', 'City', 'Monthly_Salary',
       'Years_At_Company', 'Join_Date', 'Email', 'Employment_Status',
       'Education', 'Performance_Score'],
      dtype='str')

In [68]:
df.head(1000)

,Employee_ID,Name,Age,Department,City,Monthly_Salary,Years_At_Company,Join_Date,Email,Employment_Status,Education,Performance_Score
0,E0001,Divya,22.0,HR,Chennai,NaN,3.5,NaT,employee1@example.com,active,PG,excellent
1,E0002,Meena,NaN,HR,Madurai,45000.0,14.7,2025-04-04,NaN,Resigned,UG,1.4
2,E0003,Meena,NaN,Marketing,Bengaluru,25695.0,11.5,NaT,employee3@example.com,Left,NaN,NaN
3,E0004,Anitha,NaN,IT,Chennai,NaN,NaN,NaT,NaN,ACTIVE,Post Graduate,NaN
4,E0005,Kavin,NaN,IT,Bengaluru,75570.0,5.7,NaT,NaN,Left,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...
995,E0996,Arun,32.0,Finance,Chennai,37445.0,NaN,NaT,NaN,Resigned,ug,1.7
996,E0997,Vijay,NaN,IT,Madurai,NaN,NaN,2023-08-03,employee997@example.com,Resigned,Post Graduate,0
997,E0998,Rahul,NaN,HR,Bengaluru,NaN,40.0,NaT,NaN,NaN,NaN,0
998,NaN,Sanjay,NaN,HR,Chennai,35725.0,NaN,NaT,NaN,Left,Post Graduate,0
999,E1000,Kavin,NaN,Sales,Bengaluru,NaN,NaN,NaT,NaN,Left,UG,NaN

In [69]:
df["Employment_Status"].unique()

<StringArray>
['active', 'Resigned', 'Left', 'ACTIVE', 'Active', 'left', 'On Leave', nan]
Length: 8, dtype: str

In [70]:
df["Employment_Status"] = df["Employment_Status"].str.strip().str.title()

In [71]:
df["Employment_Status"].unique()

<StringArray>
['Active', 'Resigned', 'Left', 'On Leave', nan]
Length: 5, dtype: str

# 16. Clean Education

In [72]:
print(df["Education"].unique())

<StringArray>
['PG', 'UG', nan, 'Post Graduate', 'ug ', 'Diploma']
Length: 6, dtype: str

In [73]:
df["Education"] = df["Education"].str.strip().str.replace({"PG":"Post Graduate",
                                                           "UG":"Under Graduate",
                                                           "ug":"Under Graduate"})

In [74]:
print(df["Education"].unique())

<StringArray>
['Post Graduate', 'Under Graduate', nan, 'Diploma']
Length: 4, dtype: str

# 17. Clean Performance Score

In [75]:
print(df["Performance_Score"].unique())

<StringArray>
['excellent',       '1.4',         nan,         '7',         '0',       '3.9',
       '2.2',       '1.6',       '3.2',       '3.3',       '2.0',       '3.6',
       '4.2',       '4.0',       '3.8',       '2.7',       '2.8',       '1.5',
       '3.1',       '2.4',       '4.7',       '1.2',       '4.5',       '4.9',
       '3.0',       '2.6',       '3.7',       '2.5',       '3.5',       '1.9',
       '1.7',       '4.3',       '2.9',       '4.4',       '4.1',       '1.3',
       '1.1',       '1.8',       '3.4',       '4.8',       '4.6',       '5.0',
       '2.1',       '2.3']
Length: 44, dtype: str

In [76]:
df["Performance_Score"] = pd.to_numeric(df["Performance_Score"],errors="coerce")

In [77]:
print(df["Performance_Score"].unique())

[nan 1.4 7.  0.  3.9 2.2 1.6 3.2 3.3 2.  3.6 4.2 4.  3.8 2.7 2.8 1.5 3.1
 2.4 4.7 1.2 4.5 4.9 3.  2.6 3.7 2.5 3.5 1.9 1.7 4.3 2.9 4.4 4.1 1.3 1.1
 1.8 3.4 4.8 4.6 5.  2.1 2.3]

In [78]:
print(df["Performance_Score"].dtype)

float64

In [79]:
Invalid_Score = df[(df["Performance_Score"]<1)|(df["Performance_Score"]>5)]
print(Invalid_Score["Performance_Score"])

4      7.0
7      0.0
8      7.0
12     7.0
15     0.0
      ...
988    0.0
991    7.0
996    0.0
997    0.0
998    0.0
Name: Performance_Score, Length: 433, dtype: float64

In [80]:
df.loc[(df["Performance_Score"]<1)|(df["Performance_Score"]>5),"Performance_Score"] = np.nan

In [81]:
print(df["Performance_Score"].unique())

[nan 1.4 3.9 2.2 1.6 3.2 3.3 2.  3.6 4.2 4.  3.8 2.7 2.8 1.5 3.1 2.4 4.7
 1.2 4.5 4.9 3.  2.6 3.7 2.5 3.5 1.9 1.7 4.3 2.9 4.4 4.1 1.3 1.1 1.8 3.4
 4.8 4.6 5.  2.1 2.3]

In [82]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        991 non-null    str
 1   Name               1000 non-null   str
 2   Age                341 non-null    float64
 3   Department         904 non-null    str
 4   City               871 non-null    str
 5   Monthly_Salary     512 non-null    float64
 6   Years_At_Company   407 non-null    float64
 7   Join_Date          84 non-null     datetime64[us]
 8   Email              505 non-null    str
 9   Employment_Status  890 non-null    str
 10  Education          851 non-null    str
 11  Performance_Score  179 non-null    float64
dtypes: datetime64[us](1), float64(4), str(7)
memory usage: 93.9 KB
None

Handling Missing Values

Numerical Column

# 19. Handle Missing Values in Numerical Columns

In [83]:
num_cols = df.select_dtypes(include="number").columns
print(num_cols)

Index(['Age', 'Monthly_Salary', 'Years_At_Company', 'Performance_Score'], dtype='str')

In [84]:
for i in num_cols:
    if -0.5<= df[i].skew() <= 0.5:
        df[i] = df[i].fillna(df[i].mean())
    else:
        df[i] = df[i].fillna(df[i].median())

In [85]:
df[num_cols].isna().sum()

Age                  0
Monthly_Salary       0
Years_At_Company     0
Performance_Score    0
dtype: int64

In [86]:
df[num_cols].describe()

               Age  Monthly_Salary  Years_At_Company  Performance_Score
count  1000.000000     1000.000000       1000.000000        1000.000000
mean     40.639296    53505.505000         25.875921           2.864246
std       7.211147    22887.726247          9.530363           0.480773
min      21.000000    19894.000000          0.000000           1.100000
25%      40.639296    45000.000000         25.875921           2.864246
50%      40.639296    45143.500000         25.875921           2.864246
75%      40.639296    46800.000000         25.875921           2.864246
max      60.000000   149935.000000         40.000000           5.000000

Categorical Column

# 18. Handle Missing Values in Categorical Columns

In [87]:
categorical_column = df.select_dtypes(include=object).columns
for i in categorical_column:
     df[i]=df[i].fillna(df[i].mode()[0])

C:\Users\AHALYA\AppData\Local\Temp\ipykernel_14648\2764364771.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_column = df.select_dtypes(include=object).columns

In [88]:
df[categorical_column].isna().sum()

Employee_ID          0
Name                 0
Department           0
City                 0
Email                0
Employment_Status    0
Education            0
dtype: int64

In [89]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1000 non-null   str
 1   Name               1000 non-null   str
 2   Age                1000 non-null   float64
 3   Department         1000 non-null   str
 4   City               1000 non-null   str
 5   Monthly_Salary     1000 non-null   float64
 6   Years_At_Company   1000 non-null   float64
 7   Join_Date          84 non-null     datetime64[us]
 8   Email              1000 non-null   str
 9   Employment_Status  1000 non-null   str
 10  Education          1000 non-null   str
 11  Performance_Score  1000 non-null   float64
dtypes: datetime64[us](1), float64(4), str(7)
memory usage: 93.9 KB

In [90]:
df["Employee_ID"].duplicated().sum()

np.int64(9)

In [91]:
# Recover Employee_ID and Email from original dataset

original_df = pd.read_csv("messy_employee_dataset.csv")

df["Employee_ID"] = original_df.loc[df.index, "Employee_ID"]
df["Email"] = original_df.loc[df.index, "Email"]

In [92]:
df["Email"] = df["Email"].str.strip().str.lower()

df["Email"] = df["Email"].replace("missing-email", np.nan)

In [93]:
print("Missing Employee_ID:", df["Employee_ID"].isna().sum())
print("Missing Email:", df["Email"].isna().sum())

Missing Employee_ID: 9
Missing Email: 495

In [94]:
categorical_cols = [
    "Department",
    "City",
    "Employment_Status",
    "Education"
]

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [95]:
df.isna().sum()

Employee_ID            9
Name                   0
Age                    0
Department             0
City                   0
Monthly_Salary         0
Years_At_Company       0
Join_Date            916
Email                495
Employment_Status      0
Education              0
Performance_Score      0
dtype: int64

In [96]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        991 non-null    str
 1   Name               1000 non-null   str
 2   Age                1000 non-null   float64
 3   Department         1000 non-null   str
 4   City               1000 non-null   str
 5   Monthly_Salary     1000 non-null   float64
 6   Years_At_Company   1000 non-null   float64
 7   Join_Date          84 non-null     datetime64[us]
 8   Email              505 non-null    str
 9   Employment_Status  1000 non-null   str
 10  Education          1000 non-null   str
 11  Performance_Score  1000 non-null   float64
dtypes: datetime64[us](1), float64(4), str(7)
memory usage: 93.9 KB

# 21. Save the Cleaned Dataset

In [97]:
df.to_csv("cleaned_employee_dataset.csv", index=False)